[package]
name = "firefox-cookie"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.57"
clap = { version = "3.1.18", features = ["derive"] }

[dependencies.rusqlite]
version = "0.31.0"
features = ["bundled"]